### ISSUE TITLE
Please publish latest version

### ISSUE THREAD

**Issue by Roost** [Hustle/parse-mockdb#84]
It appears the latest version published to NPM is 0.2.1. I need to use the changes from the latest package release but since it's unpublished, it is unavailable.

**Comment by noahsilas** [comment]
Hi @Roost : I've been added as a maintainer, and I've just published v0.2.5. Heads up though, I'm going to be publishing additional versions shortly that include breaking changes, so be cautious when upgrading! Details about the v0.3.0 upgrade are already in the Readme, and parse-mockdb v0.4.x will be targeting the JS SDK v2+.
